# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1a420fdc9d8bbf2c0136f05bc2cfd0aa630f1c0fa4e490f792d221695f8d423cca1b74838fc4a4838c0a469dcf5777e2f53861b2f1bb71e4d1a4c4e61706028

test:
  secret_key_base: f3b8a3089189bb7720ddeec7bdb0a47fd3a4d7c2cb91c957b8e79c9badb8c6d8f0287f7199c2c0c082c731f29bb54e4fa990573d9e9574d5450995c010388d8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
